// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PkhuKNutv3STGEkoE8bSVnCDWmO_pBE',
    appId: '1:50056890661:web:9595c24199abec6bb9f2cc',
    messagingSenderId: '50056890661',
    projectId: 'flutter-chat-app-d1cc3',
    authDomain: 'flutter-chat-app-d1cc3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d1cc3.appspot.com',
    measurementId: 'G-5EM418903H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnOFhPc_oag7xUslHHotDDqVcnw7-KXI',
    appId: '1:50056890661:android:dcea0f18664912eeb9f2cc',
    messagingSenderId: '50056890661',
    projectId: 'flutter-chat-app-d1cc3',
    storageBucket: 'flutter-chat-app-d1cc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChBBq_XJ2rtiMtM0TjuWEP5Ti5vNHlwvA',
    appId: '1:50056890661:ios:bd495fe4ac3da162b9f2cc',
    messagingSenderId: '50056890661',
    projectId: 'flutter-chat-app-d1cc3',
    storageBucket: 'flutter-chat-app-d1cc3.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChBBq_XJ2rtiMtM0TjuWEP5Ti5vNHlwvA',
    appId: '1:50056890661:ios:02f0d05289dc63ddb9f2cc',
    messagingSenderId: '50056890661',
    projectId: 'flutter-chat-app-d1cc3',
    storageBucket: 'flutter-chat-app-d1cc3.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
